### ISSUE TITLE
Receipt of IPv4 Multicast Traffic is Broken

### ISSUE THREAD

**Issue by paulobrizolara** [darconeous/smcp#39] opened 2016-07-22 16:22 UTC
Apparently, smcp (server) instances are not receiving multicast requests on ipv4 multicast adresses.
Using ipv6 link local multicast address (ff02::fd) it works.

I have tested with the 'example3.c' from master branch.
I only changed it to enforce the use of coap default port.

```
    73. smcp_plat_bind_to_port(instance,` SMCP_SESSION_TYPE_UDP, COAP_DEFAULT_PORT);
```

The request was made using smcpctl tool:

```
      ./smcpctl get "coap://224.0.1.187"
```

I made the same request using smcpctl (as client) and an example adapted from [node-coap](https://github.com/mcollina/node-coap) library (as server) and it worked.
So, the problem is not on smcpctl nor in the "network" (the client and servers was running in my machine - running Linux)

Enabling the logs (-DVERBOSE_DEBUG), i can see on smcpctl that the request is made (with multiple attempts). But the server keeps quiet.

Also, when starting the server, the logs shows that the server joined to both multicast adresses:

```
      Joined multicast group [ff02::fd]
      Joined multicast group 224.0.1.187 (224.0.1.187)
```

Looking the code, i saw that there is a separate socket for ipv4 multicast.
So, maybe this socket is not been read, or something like that.

**Comment by darconeous** [comment] 2016-07-22 19:39
Might be a interface binding problem. We are currently effectively passing `0.0.0.0` as the value for `imr_interface`, which cause the kernel to join the multicast group on all of the interfaces. But maybe that is me assuming behavior that doesn't exist. For what it's worth, the IPv6 multicast stuff does appear to work in that way.

Will continue to dig. There are plenty of IPv4 multicast examples on the net, it's just a matter of comparing a working example to the existing code and figure out what is missing.

**Comment by paulobrizolara** [comment] 2016-07-26 17:36
I have a sample that enables ipv4 and ipv6 multicast with smcp.
But it is done a little different from the library.

I used the 'MCAST_' family of options to join multicast (ex.: MCAST_JOIN_GROUP).
They allows to use almost the same code to join/leave ipv4 and ipv6 multicast addresses.
Also i used the 'udp socket' (got from smcp_plat_get_fd) and not the specifics multicast sockets.

I will try to clean up the example and put it in a gist, so you can look and test it.

**Comment by darconeous** [comment] 2016-07-26 17:55
Ooo! That sounds fantastic!

**Comment by paulobrizolara** [comment] 2016-07-26 18:58
:blush: Thanks!

The sample is here: https://gist.github.com/paulobrizolara/d369f97f6e2394846da6486227ffdaa9

**Comment by darconeous** [comment] 2016-07-27 20:04
I'll try to get that integrated into plat-bsd over the next few days. Thanks again for your help!

**Comment by paulobrizolara** [comment] 2016-07-27 20:28
Nice! Thanks!

**Comment by darconeous** [comment] 2016-07-31 22:22
Uggggh.... This is not turning out to be straightforward.

On macOS, I can only get `MCAST_JOIN_GROUP`to work (for either IPv4 or IPv6) if I specify a non-zero interface, which really sucks. I assume it works on Linux (because you are passing in zero), but I haven't tried.

I will keep banging away at it. I'll likely clean it up and have a git of a weird hybrid approach so that at least Linux works properly.

**Comment by darconeous** [comment] 2016-07-31 22:32
I'm working on this out of branch [`bug/multicast`](https://github.com/darconeous/smcp/tree/bug/multicast) if you are curious.

**Comment by paulobrizolara** [comment] 2016-08-03 16:10
Looks like there is a bug on MCAST_JOIN_GROUP on MacOs (https://bugs.php.net/bug.php?id=63000). At least for versions 10.7 and 10.8.

Following the bug report (https://github.com/php/php-src/pull/185), i have found a possible solution([multicast.c](https://github.com/igorw/php-src/blob/master/ext/sockets/multicast.c)) on php source code (the [current version of that file](https://github.com/php/php-src/blob/master/ext/sockets/multicast.c) on main repository).
They basically fallback to ipv4/ipv6 specific implementations when MCAST is not enabled.

Note: I have not tested the fix you made yet. But when i test them, i will post feedback.

**Comment by darconeous** [comment] 2016-08-04 15:12
I tried testing the fix on linux yesterday and IPv4 multicast still doesn't seem to be behaving. Very frustrating. I'll go back over your example again to try and see where I'm going wrong.

**Comment by darconeous** [comment] 2016-08-04 15:12
Although I do see the group added in the `/proc/net/igmp` file. Very strange.

**Comment by darconeous** [comment] 2016-08-04 15:13
Maybe ipv6 native sockets with ipv4 emulation can't receive multicast...?

**Comment by darconeous** [comment] 2016-08-04 17:07
Will need to test again with `SMCP_BSD_SOCKETS_NET_FAMILY` set to `AF_INET`. If that ends up working, then the problem is that IPv4-mapped IPv6 sockets can't receive IPv4 multicast.

**Comment by paulobrizolara** [comment] 2016-08-05 13:23
Hum... i believe ipv6 sockets cannot join to ipv4-mapped multicast addresses (at least on Linux).
I think i tested it and was not working.

**Comment by darconeous** [comment] 2016-08-08 18:31
Well, joining multicast groups tends to be a system-wide thing, so I create an IPv4 socket just to join the IPv4 multicast groups. It should "just work". But it doesn't, because it seems that on Linux an IPv6 socket with IPv4-mapping enabled can't receive IPv4 multicast packets, irrespective if the system has joined IPv4 multicast groups or not.

**macOS** doesn't seem to have this limitation, except that it won't do something reasonable when you specify a value of zero for the interface identifier when using `MCAST_JOIN_GROUP`: If I explicitly join individual interfaces, I can get IPv4-mapped multicast traffic on the IPv6 socket.

Ultimately, this means I can't really avoid having multiple sockets for IPv4 and IPv6 if I want IPv4 multicast to "just work". :/

**Comment by darconeous** [comment] 2016-08-08 18:33
Since IPv6 multicast is working for all the platforms I care about, and with the latest change IPv4 multicast does work if you turn off IPv6 and build for IPv4-only, I'm tempted to go ahead and take this change for the 0.07.00 release, since I don't want to hold it up too much longer.

**Comment by paulobrizolara** [comment] 2016-08-09 22:32
Well, i think i found a solution to the issue.
I have updated [the sample](https://gist.github.com/paulobrizolara/d369f97f6e2394846da6486227ffdaa9).

Now i am not using 'mcast_' options, but the specifics ipv4 and ipv6 options (see [this function](https://gist.github.com/paulobrizolara/d369f97f6e2394846da6486227ffdaa9#file-example-mcast-server-c-L173)).

The important points are:
* not using ipv4-mapped address but the ipv4 address directly (from the `sockaddr` structure, got using `getaddrinfo`)
* using the ipv4 or ipv6 options in `setsockopt` according the **address** family, not the socket family (of course, ipv6 addresses will not work with ipv4 socket).

I hope this works also on Mac (i had only tested on Linux).

**Comment by darconeous** [comment] 2016-08-10 01:19
😮

I'm amazed that works! Can you really call `IP_ADD_MEMBERSHIP` on an IPv6 socket that is configured for IPv4 mapping? I'm going to have to try this before I believe it. It seems incredible. But I guess weirder things have happened. :P

**Comment by paulobrizolara** [comment] 2016-08-10 01:51
Also seemed strange to me, but worked. However, i don't know if this is implementation specific.
I am sending a pull-request with this changes, so you can test it.

**Comment by darconeous** [comment] 2017-05-08 18:58
I'm going to go ahead and close this issue, since it is now out of the scope of SMCP ([LibNyoci](https://github.com/darconeous/libnyoci/) has taken on all of this code now).

**Closed by darconeous** 2017-05-08 18:58 UTC
Labels: bug, P1
